backend:
  name: github
  repo: imsxx/mry-blog # 确认这是你的仓库
  branch: main # 确认这是你的主分支
  site_domain: mry-blog.pages.dev # 确认这是你的 Cloudflare Pages 域名

media_folder: "static/uploads" # 这是一个占位，确保它不会引起歧义
public_folder: "/uploads"    # 同上

collections:
  - name: "test"
    label: "Test Collection"
    folder: "_test" # 确保你的 GitHub 仓库根目录下有一个名为 _test 的文件夹
    create: true
    fields:
      - {label: "Title", name: "title", widget: "string"}
